version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make deps
      - run:
          name: Run tests
          command: make test
      -run:
          name: Run docker
          command: make docker_build
workflows:
  basic:
    jobs:
      - build-and-test
