version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make deps
      - run:
          name: Run tests
          command: make test
      - run:
          name: Run docker
          command: make docker_build
      - run:
          name: Docker Push
          command: make docker_push
workflows:
  basic:
    jobs:
      - build-and-test
